// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goihlltgqqnrumzzakpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvaWhsbHRncXFucnVtenpha3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTE5ODAsImV4cCI6MjA2Njc4Nzk4MH0.nfLb3NtA2FAxf8nWNMbrzLNjOuI8dxmWt2OBj8iTeIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);